# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_useruploadvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='video_name',
            field=models.CharField(max_length=50, verbose_name='\u89c6\u9891\u540d'),
        ),
    ]
