# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-26 01:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7c7b\u540d\u79f0')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b\u540d\u79f0',
                'verbose_name_plural': '\u5206\u7c7b\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u89c6\u9891\u540d\u79f0')),
                ('desc', models.CharField(max_length=300, verbose_name='\u89c6\u9891\u63cf\u8ff0')),
                ('detail', models.TextField(verbose_name='\u89c6\u9891\u8be6\u60c5')),
                ('degree', models.CharField(choices=[('cj', '\u521d\u7ea7'), ('zj', '\u4e2d\u7ea7'), ('gj', '\u9ad8\u7ea7')], max_length=10, verbose_name='\u89c6\u9891\u7ea7\u522b')),
                ('learn_times', models.IntegerField(default=0, verbose_name='\u89c2\u770b\u65f6\u957f\uff08\u5206\u949f\uff09')),
                ('students', models.IntegerField(default=0, verbose_name='\u89c2\u770b\u4eba\u6570')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='\u89c6\u9891\u5c55\u793a\u5c01\u9762')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u8bfe\u7a0b\u7c7b\u522b')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='\u8bfe\u7a0b\u6807\u7b7e')),
                ('video_url', models.CharField(default='', max_length=200, verbose_name='\u8bbf\u95ee\u5730\u5740')),
                ('course_need', models.CharField(default='', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name='\u76f8\u5173\u63a8\u8350')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u8bfe\u7a0b\u521b\u5efa\u65f6\u95f4')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u5e03\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u89c6\u9891\u57fa\u672c\u4fe1\u606f',
                'verbose_name_plural': '\u89c6\u9891\u57fa\u672c\u4fe1\u606f',
            },
        ),
    ]
