# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-10 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='relevant_tell',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u76f8\u5173\u63a8\u8350'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m', verbose_name='\u89c6\u9891\u4e0a\u4f20'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_need',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
